### PR TITLE
227 TL about tcet linux

### PR DESCRIPTION
**Pull request by Dibya112**
## Title :
About TCET Linux

## Issue no : 
227 tl about tcet linux

## Description
Brief description about TCET Linux

## Screenshots (if applicable)
image

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Review by NikitaSShukla — APPROVED** [review]
Impressive content! Please make sure all the key words are highlighted using bold.

**Comment by Akash6222** [comment]
@NikitaSShukla ma'am review this again

**Comment by Akash6222** [comment]
Ready to merge

**Review by Akash6222 — APPROVED** [review]
GTG

**Pull request merged**
