### PR TITLE
[DOCS] Update about-tcetopensource.mdx

### PR DESCRIPTION
**Pull request by peichincc**
Add projects img to documentation

## Title :
Update about-tcetopensource.mdx

## Preview
Screenshot 2023-10-10 at 09 25 33
Screenshot 2023-10-11 at 8 35 40 AM

## Issue no : 

[[DOCS] Enhance our Documentation #251 ](https://github.com/tcet-opensource/documentation/issues/251)

## Description
Add a project image to each project to enhance the current document, user could easily understand what it looks like before opening the project website.

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

## Fix
- [x] replace the TCET Linux image
Screenshot 2023-10-07 at 8 39 06 AM

- [x] add space
- [x] add Documentation Site image
Screenshot 2023-10-11 at 16 02 36

- [x] rename Documentation Website to TCET Open Source Website

### CODE REVIEW

**Review by vish-rt — CHANGES_REQUESTED** [review]
Deployment is failing due to the following errors in the `img` tag. Have a look at it.

image

**Comment by vish-rt** [comment]
Recommend you to fetch updates from `main` before making any updates.

**Comment by peichincc** [comment]
> Deployment is failing due to the following errors in the `img` tag. Have a look at it.
> 
> image

Fixed the jsx cloing issue!

**Comment by peichincc** [comment]
@vish-rt the branch is already updated and fixed the deploy error, please have a look! Thank you!

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image

There is alignment issues in `Ongoing Projects` images

**Comment by peichincc** [comment]
> image
> 
> There is alignment issues in `Ongoing Projects` images

@himanshu-03 
I have added the line to make the image align as Live Projects.

**Comment by peichincc** [comment]
The preview of this PR

Screenshot 2023-10-10 at 09 25 33
Screenshot 2023-10-11 at 8 35 40 AM

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
There is wrong image placed in place of TCET Linux

**Comment by peichincc** [comment]
> There is wrong image placed in place of TCET Linux

Fixed!

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
It would be great to have some spaces and also the documentation website image is missing

**Comment by peichincc** [comment]
> It would be great to have some spaces and also the documentation website image is missing

@himanshu-03 ok, maybe one more line between the image and the bold text, should be fine. And also, which one is exactly the documentation website? because I could not find it in https://github.com/tcet-opensource/.github/blob/main/profile/README.md

**Comment by himanshu-03** [comment]
> > It would be great to have some spaces and also the documentation website image is missing
> 
> @himanshu-03 OK, maybe one more line between the image and the bold text, should be fine.
> 
> And also, which one is exactly the documentation website? because I could not find it in https://github.com/tcet-opensource/.github/blob/main/profile/README.md If the website link is provided, I could add the extra image.
> 
> And would like to confirm if is there anything to change for this Update?

Okay so basically there's a little change you can change the name of Documentation Website to TCET Open Source Website because we have our documentation on our website itself.

For the screenshot, you can take a SS of this page and upload this image. [TCET Open Source Website](https://opensource.tcetmumbai.in/)

**Comment by peichincc** [comment]
> > > It would be great to have some spaces and also the documentation website image is missing
> > 
> > 
> > @himanshu-03 OK, maybe one more line between the image and the bold text, should be fine.
> > And also, which one is exactly the documentation website? because I could not find it in https://github.com/tcet-opensource/.github/blob/main/profile/README.md If the website link is provided, I could add the extra image.
> > And would like to confirm if is there anything to change for this Update?
> 
> Okay so basically there's a little change you can change the name of Documentation Website to TCET Open Source Website because we have our documentation on our website itself.
> 
> For the screenshot, you can take a SS of this page and upload this image. [TCET Open Source Website](https://opensource.tcetmumbai.in/)
> 
> Also, the spacings which you gave didnt solved the issue. Try keeping `<br />` in a seperate line and leave a line after the command, I think it will work then
> 
> image

@himanshu-03 
I added one more <br/>, now it looks a bit far, maybe you could check the preview to see (just one <br/> added now)

And for the documentation website image and rename, are all done.

In the commits so far:
- [ ] Add space
- [ ] Add image to documentation website
- [ ] Rename documentation website

**Comment by peichincc** [comment]
@himanshu-03 @vish-rt could you please check whether this is ok for now? Thank you :)

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
Can you remove the extra `<br/>` tags beside the Project name. IDTS they are required

**Comment by peichincc** [comment]
> Can you remove the extra `<br/>` tags beside the Project name. IDTS they are required

@himanshu-03 done! Please check, thank you!

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by peichincc** [comment]
Can @vish-rt check if is it all good now? Thank you!

**Review by vish-rt — APPROVED** [review]
Will be shipped to production soon!

**Comment by vish-rt** [comment]
@peichincc thank you for contributing to this repository! We are merging your pull request 🚀

**Pull request merged**
