### PR TITLE
[ADDED] The header component doc for RS 

### PR DESCRIPTION
**Pull request by preyanskhasingh**
I have completed the assigned issues as of issue no. #144

### CODE REVIEW

**Comment by preyanskhasingh** [comment]
I have updated the documentation for header of RS (Resume Screener) Website as of issue no #144

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image


Cannot see this mobile nav code anywhere!

**Comment by preyanskhasingh** [comment]
I have added the code with its respective representation. Issue no. #144

**Comment by himanshu-03** [comment]
We just don't have to break the code instead we need to explain the things written in code!

**Comment by preyanskhasingh** [comment]
[ADDED] Have made the required changes with the code. Issue no. #144

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Pull request merged**
