### PR TITLE
Blockchain- Future of tomorrow

### PR DESCRIPTION
**Pull request by kashish-51**
## Title :
Blockchain

## Issue no : 
#249 

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Comment by vish-rt** [comment]
Sync up your fork with our repo and resolve conflicts so I can merge your PR!

**Comment by kashish-51** [comment]
synced repository. Please check now.

**Review by NikitaSShukla — APPROVED** [review]
Amazing  job! content written very well.

**Comment by kashish-51** [comment]
> Amazing job! content written very well.

Thankyou

**Pull request merged**
