### PR TITLE
[ADDED] T&P Frontend Documentation

### PR DESCRIPTION
**Pull request by SakshiPorwal**
Completed Top Recruiters page documentation

### CODE REVIEW

**Review by himanshu-03 — COMMENTED** [review]
LGTM!
Top Recruiters Component Completed

**Review by himanshu-03 — COMMENTED** [review]
LGTM!
Footer done

**Comment by aryadubey03** [comment]
Top placed students section is completed.

**Review by himanshu-03 — COMMENTED** [review]
T&P Website Frontend Docs Completed
- Components Description left
- Directory Structure left

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Shipping to main!

**Pull request merged**
